name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 0.14.2
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/flame

flutter:
  uses-material-design: false

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.13.1
  ordered_set: ^1.1.2
  path_provider: ^1.2.0
  box2d_flame: ^0.4.4
  synchronized: ^2.1.0+1
  tiled: ^0.2.1
  convert: ^2.1.1
  flutter_svg: ^0.13.1
  flare_flutter: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.6.0"
